[package]
name = "rust_mongo_test"
version = "0.1.0"
authors = ["Mingjue <mingjue@vt.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = { version = "0.4.0", features = ["ssl"] }
